name: Selenium WebDriver CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Install dependencies
      run: dotnet restore SeleniumBasicExercise.sln
    - name: Build
      run: dotnet build SeleniumBasicExercise.sln --no-restore
    - name: Fix permissions for selenium-manager
      run: |
        chmod +x ./TestProject1/bin/Debug/net6.0/selenium-manager/linux/selenium-manager || true
        chmod +x ./TestProject2/bin/Debug/net6.0/selenium-manager/linux/selenium-manager || true
        chmod +x ./TestProject3/bin/Debug/net6.0/selenium-manager/linux/selenium-manager || true
    - name: Run TestProject1 tests
      run: dotnet test TestProject1 --no-build --verbosity normal
    - name: Run TestProject2 tests
      run: dotnet test TestProject2 --no-build --verbosity normal
    - name: Run TestProject3 tests
      run: dotnet test TestProject3 --no-build --verbosity normal
